version: "3.1"

services:

  junkstarter-database:
    image: junkstarter-db
    ports:
      - "1433:1433"
    networks:
      - app-net

  junkstarter-api:
    image: junkstarter-api
    ports:
      - "8080:8080" 
    depends_on:
      - junkstarter-database
    networks:
      - app-net

networks:
  app-net:
    external:
      name: nat
