matrix:
  include:
    - language: java
      name: "BE Unit Tests"
      sudo: required
      services:
        - docker

      env:
        - DOCKER_COMPOSE_VERSION=1.4.2
      before_install:
        - sudo rm /usr/local/bin/docker-compose
        - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
        - chmod +x docker-compose
        - sudo mv docker-compose /usr/local/bin
        # - docker-compose up

    - language: node_js
      name: "FE Unit Tests"
      cache: yarn
      node_js:
        - "10.10.0"
      env:
        - CI=true
      before_install:
        - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.9.4
        - export PATH="$HOME/.yarn/bin:$PATH"
        - cd app/frontend
        - yarn install
      script:
        - yarn test
