matrix:
  include:
    - language: java
      name: "BE Unit Tests"
      before_install:
        - cd app

    - language: node_js
      name: "FE Unit Tests"
      cache: yarn
      node_js:
        - "10.10.0"
      env:
        - CI=true
      before_install:
        - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.9.4
        - export PATH="$HOME/.yarn/bin:$PATH"
        - cd app/frontend
      script:
        - yarn test
