apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: appserver
  name: appserver
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: appserver
    spec:
      containers:
      - image: martinwheeler/junkstarter-api:7dae7c810d29407d53dd2495a4cb77d5f8d09aae
        imagePullPolicy: IfNotPresent
        name: appserver
        ports:
        - containerPort: 8080
        - containerPort: 5005
        resources: {}
      restartPolicy: Always
status: {}
