---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: database
  name: database
spec:
  ports:
  - name: "5432"
    port: 5432
    targetPort: 5432
  selector:
    io.kompose.service: database
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: database
  name: database
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: database
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          value: atsea
        - name: POSTGRES_PASSWORD
          value: gordonpass
        - name: POSTGRES_USER
          value: gordonuser
        image: martinwheeler/junkstarter-db:d8dcc8af8863143415805badcf78a9667bbb3594
        imagePullPolicy: IfNotPresent
        name: database
        ports:
        - containerPort: 5432
        resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: appserver
  name: appserver
spec:
  type: NodePort
  ports:
  - name: "80"
    port: 80
    targetPort: 8080
  - name: "5005"
    port: 5005
    targetPort: 5005
  selector:
    io.kompose.service: appserver
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: appserver
  name: appserver
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: appserver
    spec:
      containers:
      - image: martinwheeler/junkstarter-api:d8dcc8af8863143415805badcf78a9667bbb3594
        imagePullPolicy: IfNotPresent
        name: appserver
        ports:
        - containerPort: 8080
        - containerPort: 5005
        resources: {}
      restartPolicy: Always
status: {}
