version: "3.1"

services:
  # Not really sure we need this...
  # Can probably create a better NGINX config to expose both the API and the APP
  # reverse_proxy:
  #   build: ./reverse_proxy
  #   user: nginx

  database:
    build:
       context: database
       dockerfile: Dockerfile
    image: martinwheeler/junkstarter-db
    user: postgres
    environment:
      POSTGRES_USER: gordonuser
      POSTGRES_PASSWORD: gordonpass
      POSTGRES_DB: atsea
    ports:
      - "5432:5432"
    secrets:
      - postgres-password

  appserver:
    build:
       context: app
       dockerfile: Dockerfile
    image: martinwheeler/junkstarter-api
    user: gordon
    ports:
      - "8080:8080" 
      - "5005:5005"
    secrets:
      - postgres-password
    links:
      - database

  # Not sure how this fits into the API backend?
  # Guess we will have to find out when we start taking payments
  # payment_gateway:
  #   build:
  #     context: payment_gateway
  #   secrets:
  #     - payment-token
  #   links:
  #     - appserver

# secrets:
#   postgres-password:
#     file: ./devsecrets/postgres-password
#   payment-token:
#     file: ./devsecrets/payment-token
