FROM node:latest
WORKDIR /usr/src/junkstarter/app/frontend
COPY frontend .
RUN yarn
RUN yarn build

FROM maven:latest
WORKDIR /usr/src/junkstarter
COPY pom.xml .
RUN mvn -B -f pom.xml -s /usr/share/maven/ref/settings-docker.xml dependency:go-offline
COPY . .
RUN mvn -B -s /usr/share/maven/ref/settings-docker.xml package -DskipTests

FROM java:8-jdk-alpine

WORKDIR /static
COPY --from=0 /usr/src/junkstarter/app/frontend/build/ .
WORKDIR /app
COPY --from=1 /usr/src/junkstarter/target/JunkStarter-0.0.1-SNAPSHOT.jar .
EXPOSE 5005
ENTRYPOINT ["java", "-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5005","-jar", "/app/JunkStarter-0.0.1-SNAPSHOT.jar"]
CMD ["--spring.profiles.active=postgres"]
