---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: junkstarter-beta
  namespace: default
  labels:
    app: junkstarter-beta
spec:
  replicas: 1
  selector:
    matchLabels:
      app: junkstarter-beta

  strategy:
    type: RollingUpdate

  template:
    metadata:
      labels:
        app: junkstarter-beta

    spec:
      containers:
        - name: junkstarter-api
          image: martinwheeler/junkstarter-api
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          volumeMounts:
            - name: junkstarter-secrets
              mountPath: "/run/secrets"
              readOnly: true
        # - name: junkstarter-db
        #   image: martinwheeler/junkstarter-db
        #   imagePullPolicy: IfNotPresent
        #   ports:
        #     - containerPort: 5432
        #   volumeMounts:
        #     - name: junkstarter-secrets
        #       mountPath: "/run/secrets"
        #       readOnly: true
        # - name: junkstarter-payment
        #   image: martinwheeler/junkstarter-payment
        #   imagePullPolicy: IfNotPresent
        #   ports:
        #     - containerPort: 8081
        #   volumeMounts:
        #     - name: junkstarter-secrets
        #       mountPath: "/run/secrets"
        #       readOnly: true
      volumes:
      - name: junkstarter-secrets
        secret:
          secretName: production-secrets
          items:
          - key: payment-token
            path: payment-token
          - key: postgres-password
            path: postgres-password
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: junkstarter-beta-hpa
  namespace: default
  labels:
    app: junkstarter-beta
spec:
  scaleTargetRef:
    kind: Deployment
    name: junkstarter-beta
    apiVersion: apps/v1beta1
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
---
apiVersion: v1
kind: Service
metadata:
  name: junkstarter-beta
  labels:
    app: junkstarter-beta
spec:
  type: ClusterIP
  ports:
    - port: 80
  selector:
    app: junkstarter-beta
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: junkstarter-beta-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /api
spec:
  rules:
  - host: beta.junkstarter.io
    http:
      paths:
      - path: /api
        backend:
          serviceName: junkstarter-beta
          servicePort: 80