apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: junkstarter-beta
spec:
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: junkstarter

  template:
    metadata:
      labels:
        app: junkstarter

    spec:
      containers:
        - name: junkstarter-api
          image: martinwheeler/junkstarter-api
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          volumeMounts:
            - name: junkstarter-secrets
              mountPath: "/run/secrets"
              readOnly: true
      volumes:
        - name: junkstarter-secrets
        secret:
          secretName: postgres-password

---
apiVersion: v1
kind: Service
metadata:
  name: junkstarter-beta
  labels:
    app: junkstarter
spec:
  type: ClusterIP
  ports:
    - port: 80
  selector:
    app: junkstarter
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: junkstarter-beta-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /api
spec:
  rules:
  - host: app.beta.junkstarter.io
    http:
      paths:
      - path: /api
        backend:
          serviceName: junkstarter-beta
          servicePort: 80